### ISSUE TITLE
Check whether Interstitial, Reward ads are loaded

### ISSUE THREAD

**Issue by mjapps-games** [EYALIN/community-admob-plus#10]
After loading any ad we have a callback event. But if want to check a specific ad at any time that if it is available/loaded or not how we can do it?

Do we have `isLoaded` function to check for Reward, Interstitial, RewardInterstitial ads. How to do it?

**Comment by EYALIN** [comment]
@mjapps-games the is ".isLoaded()" for all ad types, no?

**Comment by EYALIN** [comment]
closed due to inactivity
