### ISSUE TITLE
testmode ads working ok but real ads - iOS

### ISSUE THREAD

**Issue by matrixreal** [EYALIN/community-admob-plus#12]
Hello,
When i set admob.configure({testDeviceIds: ['5c9e03fa207f0b705e48a5cc78242c68']}); test ads are working but when i delete it it's not working.
Any helps please?
Thanks

**Comment by matrixreal** [comment]
@EYALIN 
any solution?

**Comment by matrixreal** [comment]
@EYALIN 
what do you think?

**Comment by matrixreal** [comment]
Thanks for answer but i think that you did not undrstand my point.
when i use : 
admob.requestTrackingAuthorization().then(() => {
admob.start().then(() => {
**admob.configure({testDeviceIds: ['5c9e03fa207f0b705e48a5cc78242c68']});**
banner = new admob.BannerAd(
{adUnitId: 'ca-app-pub-472249365416262210307243/6810357243', offset: 0});
});
});
i get test ads banner
but when i delete the admob.configure({testDeviceIds: ['5c9e03fa207f0b705e48a5cc78242c68']});
i don't get any banner ads.
this is tested on ios real device.

**Comment by EYALIN** [comment]
@matrixreal if the id you put here is a real id, so you should put your device as a test device in admob settings

**Comment by matrixreal** [comment]
@EYALIN 
i want to publish my app to the store without test device i put the true banner id but i still don't get any ads.

**Comment by EYALIN** [comment]
@matrixreal so don't be worry about, it whould work
but if you want to see the ads without the testing device, you need to add your device in admob settings as a testing device.
but even if that will not work for you, it will work in production.

**Comment by EYALIN** [comment]
closed due to inactivity
