### ISSUE TITLE
I get these Xcode errors inside of AMBCore and AMBBanner

### ISSUE THREAD

**Issue by therealPaulPlay** [EYALIN/community-admob-plus#2]
**Describe the bug**
I get these 2 Xcode errors when trying to build with the plugin (see screenshots)

**To Reproduce**
1. Build with cordova and install the pods
2. See the issue inside of xcode (latest version)

**Expected behavior**
There should be no errors 

**Screenshots**
<img width="1132" alt="Bildschirmfoto_2023-04-23_um_21 46 56" src="https://user-images.githubusercontent.com/80539587/233862456-487eadaf-8fc6-4112-a59e-5c8547976cce.png">
<img width="1012" alt="Bildschirmfoto_2023-04-23_um_21 51 57" src="https://user-images.githubusercontent.com/80539587/233862461-99a7f89c-ab83-46cd-9e48-463ff74f6875.png">

**Environment**
Using construct 3 and building with cordova and this addon.

**Comment by ollm** [comment]
Try changing the swift version to a lower one, for example 5 or 4.2, I use version 5 and it works correctly for me, although this will have to be fixed in the future.

[How to change Swift in Xcode?](https://stackoverflow.com/questions/56894082/how-to-change-swift-version-from-5-to-4-in-xcode)

**Comment by EYALIN** [comment]
@therealPaulPlay  did you try the solution?

**Comment by therealPaulPlay** [comment]
Sorry, I have fixed this a few weeks ago. Yes, this is the solution. Not a lower one though, but rather a higher one (5 works). It defaults to 4, which does not work

**Comment by EYALIN** [comment]
got solved. thanks @ollm
