### ISSUE TITLE
Would it support android target api 33?

### ISSUE THREAD

**Issue by degroundshaker** [EYALIN/community-admob-plus#7]
Google has sent this warning to apps that does not target API 33

**To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From 31 Aug 2023, if your target API level is not within one year of the latest Android release, you won't be able to update your app.**

So, I was wondering if this plugin would work ok with this upgrade from api 31 to 33?

**Comment by EYALIN** [comment]
@degroundshaker support 33
