### ISSUE TITLE
Problem with Cordova consent and AdMob

### ISSUE THREAD

**Issue by konguele** [EYALIN/community-admob-plus#9]
Good Morning,

I have created my game with Gdevelop, for Android it has worked perfectly, but on iOS I find this recurring error. I don't know what else to do and I'm desperate, because I can't find a solution. I don't know if it's a conflict between cordova-plugin-consent and admob-plus-cordova, but I keep getting this error and I don't know what to do.

I```
nstalling "admob-plus-cordova" for ios

[!] The `Jabali Espacial [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Jabali Espacial [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.release.xcconfig'. This can lead to problems with the CocoaPods installation
Adding admob-plus-cordova to package.json
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Failed to install 'cordova-plugin-consent': Error: Command failed with exit code 1: pod install --verbose
  Preparing

[!] CocoaPods could not find compatible versions for pod "GoogleUserMessagingPlatform":
  In snapshot (Podfile.lock):
    GoogleUserMessagingPlatform (= 2.1.0, >= 1.1)

  In Podfile:
    GoogleUserMessagingPlatform (~> 2.0.0)

Specs satisfying the `GoogleUserMessagingPlatform (~> 2.0.0), GoogleUserMessagingPlatform (= 2.1.0, >= 1.1)` dependency were found, but they required a higher minimum deployment target.
```

```
Adding admob-plus-cordova to package.json
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Failed to install 'cordova-plugin-consent': Error: Command failed with exit code 1: pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Jabali Espacial`: (``)

Finding Podfile changes
  A GoogleUserMessagingPlatform
  - Google-Mobile-Ads-SDK

```
I add the complete log in case it can help.

Thanks for your help.

**Comment by EYALIN** [comment]
@konguele please try our new forked plugin for consent
"community-cordova-plugin-consent" and also it seems that you are using not this plugin for "Admob"
please use "community-admob-plus-cordova"
i also follow "admob-plus-cordova" and in the moment it will work, i will move there

**Comment by EYALIN** [comment]
closed due to inactivity
